import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import content from './content.json';
import './style.css';

const books = [
  {slug:'atlas',number:'01',type:'MANUAL PRINCIPAL',title:'Atlas Visual de Farmacología Veterinaria',short:'Farmacología, sin perderse entre cientos de páginas.',description:'24 fichas de consulta: fundamentos, clases farmacológicas, mecanismos y precauciones para perros y gatos.',count:'24 fichas',kit:'Esencial',accent:'coral',pdf:'01_Atlas_Visual_Farmacologia_Veterinaria.pdf',symbol:'✳'},
  {slug:'quiz',number:'02',type:'PRÁCTICA ACTIVA',title:'Quiz de Farmacología Veterinaria',short:'Aprender también es ponerse a prueba.',description:'20 preguntas con explicación de cada respuesta para reforzar los conceptos del atlas.',count:'20 preguntas',kit:'Esencial',accent:'sage',pdf:'02_Quiz_Farmacologia_Veterinaria.pdf',symbol:'?̊'},
  {slug:'laboratorio',number:'03',type:'GUÍA DE CONSULTA',title:'Guía Visual de Laboratorio Veterinario',short:'Leer resultados con más contexto.',description:'Una ruta visual para revisar muestra, hemograma, bioquímica y urianálisis.',count:'8 temas',kit:'Profesional',accent:'blue',pdf:'03_Guia_Visual_Laboratorio_Veterinario.pdf',symbol:'⌁'},
  {slug:'examenes',number:'04',type:'GUÍA DE RAZONAMIENTO',title:'Guía de Interpretación de Exámenes',short:'Del resultado alterado a la pregunta correcta.',description:'Ocho rutas de razonamiento para integrar hallazgos de laboratorio con la clínica.',count:'8 rutas',kit:'Profesional',accent:'ochre',pdf:'04_Guia_Interpretacion_Examenes_Veterinarios.pdf',symbol:'◌'},
  {slug:'fichas',number:'05',type:'CASOS PARA ESTUDIO',title:'Fichas Clínicas Veterinarias',short:'Practica cómo ordenar la información.',description:'Ocho escenarios guiados con datos a reunir, prioridades y preguntas para discusión.',count:'8 casos',kit:'Profesional',accent:'lavender',pdf:'05_Fichas_Clinicas_Veterinarias.pdf',symbol:'✦'},
  {slug:'soap',number:'06',type:'PLANTILLAS PRÁCTICAS',title:'Método SOAP Veterinario',short:'Documentar también es razonar.',description:'Guía y cuatro ejercicios para registrar información subjetiva, objetiva, evaluación y plan.',count:'4 ejercicios',kit:'Profesional',accent:'mint',pdf:'06_Metodo_SOAP_Veterinario.pdf',symbol:'▦'},
];

const pdfUrl = book => '/materiales/' + book.pdf;
const getSlug = () => location.pathname.match(/^\/material\/([^/]+)/)?.[1] || '';

function Icon({name,size=20}) {
  const paths = {
    arrow:<><path d="M4 12h15M13 6l6 6-6 6"/></>,
    back:<><path d="M20 12H5m6 6-6-6 6-6"/></>,
    download:<><path d="M12 3v12m-5-5 5 5 5-5M4 17v3h16v-3"/></>,
    book:<><path d="M12 7c-2.5-2-5-2.5-9-2v14c4-.5 6.5 0 9 2 2.5-2 5-2.5 9-2V5c-4-.5-6.5 0-9 2Zm0 0v14"/></>,
    grid:<><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></>,
    check:<><path d="m4 12 5 5L20 6"/></>,
    close:<><path d="m5 5 14 14M19 5 5 19"/></>,
    search:<><circle cx="11" cy="11" r="7"/><path d="m16 16 5 5"/></>,
  };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>;
}

function Cover({book,large=false}) {return <div className={`cover cover-${book.accent} ${large?'cover-large':''}`}>
  <div className="cover-top"><span>ATLAS<br/>VETERINARIO</span><span className="cover-orbit">{book.symbol}</span></div>
  <div className="cover-art"><span className="art-ring"/><span className="art-ring art-ring-two"/><span className="art-symbol">{book.symbol}</span></div>
  <div className="cover-bottom"><span className="cover-rule"/><span className="cover-title">{book.title}</span><span className="cover-edition">EDICIÓN DIGITAL · 2026</span></div>
</div>}

function BookCard({book,onOpen}) {return <button className="book-card" onClick={()=>onOpen(book.slug)} aria-label={'Abrir '+book.title}>
  <div className="book-image"><Cover book={book}/></div>
  <div className="book-info"><span className="eyebrow">{book.number} / {book.type}</span><h3>{book.title}</h3><p>{book.description}</p><div className="book-bottom"><span>{book.count}</span><span className="circle-arrow"><Icon name="arrow" size={19}/></span></div></div>
</button>}

function Nav({navigate,detail}) {return <header className="site-header"><div className="header-inner">
  <button className="brand" onClick={()=>navigate('')} aria-label="Volver a la biblioteca"><span className="brand-mark">✳</span><span>atlas<span className="brand-light">veterinario</span><small>ESTUDIO VISUAL</small></span></button>
  <nav aria-label="Navegación principal"><button className={!detail?'active':''} onClick={()=>navigate('')}>Biblioteca</button><button onClick={()=>{navigate('');setTimeout(()=>document.getElementById('materiales')?.scrollIntoView({behavior:'smooth'}),30)}}>Materiales</button></nav>
  <span className="header-tag">6 recursos digitales <span>↗</span></span>
</div></header>}

function Home({navigate}) {const [filter,setFilter]=useState('Todos'); const [query,setQuery]=useState(''); const visible=books.filter(b=>(filter==='Todos'||b.kit===filter)&&(b.title+' '+b.description).toLowerCase().includes(query.toLowerCase()));
return <><section className="hero"><div className="hero-inner"><div className="hero-copy"><div className="hero-kicker"><span className="line"/> FARMACOLOGÍA VETERINARIA, MÁS CLARA</div><h1>Una biblioteca para <em>entender,</em><br/> consultar y practicar.</h1><p>Seis materiales pensados para estudiar farmacología veterinaria de forma organizada, con preguntas, escenarios y guías que te acompañan más allá de la teoría.</p><button className="primary-button" onClick={()=>document.getElementById('materiales').scrollIntoView({behavior:'smooth'})}>Explorar los materiales <Icon name="arrow"/></button><div className="hero-meta"><span><strong>06</strong> recursos digitales</span><span className="meta-divider"/><span><strong>01</strong> biblioteca para volver a consultar</span></div></div>
<div className="hero-stage" aria-hidden="true"><div className="stage-glow"/><div className="stage-caption">APRENDER · CONSULTAR · APLICAR</div><div className="stage-book stage-book-left"><Cover book={books[2]}/></div><div className="stage-book stage-book-right"><Cover book={books[4]}/></div><div className="stage-book stage-book-front"><Cover book={books[0]}/></div><div className="stage-sticker">6<br/><small>GUÍAS</small></div></div></div></section>
<main id="materiales" className="library-section"><div className="section-top"><div><span className="eyebrow">LA COLECCIÓN COMPLETA</span><h2>Tu biblioteca de estudio<span className="dot">.</span></h2><p>Empieza por los fundamentos y profundiza con casos, laboratorio y práctica.</p></div><span className="section-counter">01 — 06</span></div>
<div className="toolbar"><div className="filters" aria-label="Filtrar materiales">{['Todos','Esencial','Profesional'].map(v=><button key={v} className={filter===v?'selected':''} onClick={()=>setFilter(v)}>{v}<span>{v==='Todos'?6:v==='Esencial'?2:4}</span></button>)}</div><label className="search"><Icon name="search" size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar material" aria-label="Buscar material"/></label></div>
<div className="books-grid">{visible.map(book=><BookCard key={book.slug} book={book} onOpen={navigate}/>)}</div>{visible.length===0&&<div className="empty">No encontramos materiales con esa búsqueda.</div>}
</main><section className="closing"><div><span className="eyebrow">UN SISTEMA DE ESTUDIO</span><h2>De la teoría a la pregunta clínica.</h2></div><div><p>Consulta un concepto en el atlas, refuérzalo en el quiz y úsalo como punto de partida para pensar casos y resultados.</p><button onClick={()=>navigate('atlas')}>Comenzar por el Atlas <Icon name="arrow"/></button></div></section></>}

function Sidebar({book,items,active,setActive}) {return <aside className="reader-sidebar"><div className="sidebar-head"><span className="eyebrow">CONTENIDO</span><span>{String(items.length).padStart(2,'0')} SECCIONES</span></div><div className="sidebar-scroll">{items.map((item,i)=><button key={i} className={active===i?'current':''} onClick={()=>{setActive(i);window.scrollTo({top:0,behavior:'smooth'})}}><span>{String(i+1).padStart(2,'0')}</span>{item}</button>)}</div><a className="sidebar-download" href={pdfUrl(book)} download><Icon name="download" size={18}/> Descargar PDF</a></aside>}

function Field({label,children}) {return <div className="field"><span>{label}</span><p>{children}</p></div>}
function Tip({children}) {return <div className="tip"><span className="tip-icon">✳</span><div><strong>PARA RECORDAR</strong><p>{children}</p></div></div>}
function Points({items}) {return <ul className="points">{items.map((v,i)=><li key={i}><Icon name="check" size={18}/><span>{v}</span></li>)}</ul>}

function Quiz({active,setActive}) {const [answers,setAnswers]=useState({});let q=content.questions[active];let selected=answers[active];return <><div className="quiz-progress"><span>PREGUNTA {String(active+1).padStart(2,'0')} / 20</span><div><span style={{width:`${(active+1)*5}%`}}/></div></div><h2 className="question">{q[0]}</h2><div className="options">{q[1].map((o,i)=>{const letter='ABC'[i];return <button key={i} className={selected===letter?'picked '+(letter===q[2]?'correct':'incorrect'):''} onClick={()=>setAnswers({...answers,[active]:letter})}><span>{letter}</span>{o}{selected===letter&&<Icon name={letter===q[2]?'check':'close'} size={19}/>}</button>})}</div>{selected&&<div className={'feedback '+(selected===q[2]?'feedback-good':'feedback-retry')}><strong>{selected===q[2]?'¡Correcto!':'La respuesta correcta es '+q[2]+'.'}</strong><p>{q[3]}</p><small>REFERENCIA · {q[4]}</small></div>}<div className="reader-actions"><button disabled={active===0} onClick={()=>setActive(active-1)}><Icon name="back" size={17}/> Anterior</button><button disabled={active===19} onClick={()=>setActive(active+1)}>Siguiente <Icon name="arrow" size={17}/></button></div></>}

function Soap({active}) {const [values,setValues]=useState({});const key=active;const fields=[['S · Subjetivo','Relato del tutor, cronología y antecedentes'],['O · Objetivo','Exploración, constantes, peso y pruebas'],['A · Análisis','Problemas, diferenciales y grado de certeza'],['P · Plan','Pruebas, indicaciones, seguimiento y señales de alarma']];return <><p className="lead">Practica cómo documentar un caso. Tus notas se conservan solo en este navegador.</p>{fields.map(([label,placeholder],i)=><label className="soap-field" key={label}><span>{label}</span><textarea value={values[key+'-'+i]??localStorage.getItem('soap-'+key+'-'+i)??''} placeholder={placeholder} onChange={e=>{let v=e.target.value;setValues({...values,[key+'-'+i]:v});localStorage.setItem('soap-'+key+'-'+i,v)}}/></label>)}<Tip>Distingue siempre los datos reportados de los observados y documenta la incertidumbre.</Tip></>}

function ReaderBody({book,active,setActive}) {if(book.slug==='atlas'){const item=content.atlas[active];return <><div className="reader-pill">FICHA {item[0]} / 24</div><h1>{item[1]}</h1><p className="lead">Una idea a la vez. Relaciona mecanismo, paciente y objetivo clínico.</p><div className="hero-definition"><span>{item[2].toUpperCase()}</span><p>{item[3]}</p></div><div className="reader-columns"><Field label={item[4]}>{item[5]}</Field><Field label={item[6]}>{item[7]}</Field></div><Tip>Consulta la ficha técnica del producto y la situación del paciente antes de cualquier decisión de tratamiento.</Tip><Source id={item[8]}/></>}
if(book.slug==='quiz')return <Quiz active={active} setActive={setActive}/>;
if(book.slug==='laboratorio'){const item=content.lab[active];return <><div className="reader-pill">RUTA {String(active+1).padStart(2,'0')} / 08</div><h1>{item[0]}</h1><p className="lead">{item[1]}</p><Points items={item[2]}/><Tip>{item[3]}</Tip><Source id={active===1||active===2||active===3||active===4?'M4':active===6?'M6':'M5'}/></>}
if(book.slug==='examenes'){const item=content.interpret[active];return <><div className="reader-pill">RUTA {String(active+1).padStart(2,'0')} / 08</div><h1>{item[0]}</h1><p className="lead">Del dato al razonamiento clínico: confirma, contextualiza y define qué falta saber.</p><div className="reader-columns"><Field label="01 · CONFIRMAR">{item[1]}</Field><Field label="02 · CONTEXTUALIZAR">{item[2]}</Field></div><Tip>{item[3]}</Tip><Source id={active===7?'M6':active===1||active===2||active===0?'M4':'M5'}/></>}
if(book.slug==='fichas'){const item=content.cases[active];return <><div className="reader-pill">ESCENARIO {String(active+1).padStart(2,'0')} / 08</div><h1>{item[0]}</h1><p className="lead">Una ficha de discusión, no una pauta de prescripción. Detente a ordenar lo que sabes.</p><Field label="DATOS A REUNIR">{item[1]}</Field><Field label="PRIORIDAD DE RAZONAMIENTO">{item[2]}</Field><div className="question-card"><span>PREGUNTAS PARA DISCUSIÓN</span><p>{item[3]}</p></div><Tip>Escribe tres diferenciales, un dato decisivo y un criterio de reevaluación.</Tip><Source id={item[4]}/></>}
return <><div className="reader-pill">{active===0?'MÉTODO':'EJERCICIO '+String(active).padStart(2,'0')+' / 04'}</div><h1>{active===0?'Una estructura para pensar y documentar.':['','Perro · dolor musculoesquelético','Gato · signos urinarios','Perro · prurito','Gato · vómitos'][active]}</h1>{active===0?<><p className="lead">SOAP ordena el relato, los datos observados, el análisis y el plan. Es una herramienta de documentación, no un diagnóstico automático.</p>{[['S','Subjetivo','Lo que comunica el tutor: motivo, cronología, antecedentes y tratamientos.'],['O','Objetivo','Lo que puede medirse u observarse: exploración, constantes y pruebas.'],['A','Análisis','Problemas y diagnósticos diferenciales, con su grado de certeza.'],['P','Plan','Pruebas, tratamiento indicado, comunicación y seguimiento.']].map(x=><div className="soap-step" key={x[0]}><span>{x[0]}</span><div><h3>{x[1]}</h3><p>{x[2]}</p></div></div>)}<Tip>La fecha, especie, peso, unidades y responsables hacen que una nota sea más útil.</Tip></>:<Soap active={active}/>}</>}

function Source({id}) {const x=content.SOURCES[id];return x?<div className="source">FUENTE DE CONSULTA · <a href={x[1]} target="_blank" rel="noreferrer">{x[0]} ↗</a></div>:null}

function Detail({book,navigate}) {const [active,setActive]=useState(0);useEffect(()=>setActive(0),[book.slug]);let items=book.slug==='atlas'?content.atlas.map(x=>x[1]):book.slug==='quiz'?content.questions.map((x,i)=>'Pregunta '+String(i+1).padStart(2,'0')):book.slug==='laboratorio'?content.lab.map(x=>x[0]):book.slug==='examenes'?content.interpret.map(x=>x[0]):book.slug==='fichas'?content.cases.map(x=>x[0]):['El método SOAP','Dolor musculoesquelético','Signos urinarios','Prurito','Vómitos'];return <main className="detail"><div className="detail-intro"><button className="back-link" onClick={()=>navigate('')}><Icon name="back" size={17}/> Volver a la biblioteca</button><div className="detail-heading"><div className="detail-cover"><Cover book={book}/></div><div><span className="eyebrow">{book.number} / {book.type} · KIT {book.kit.toUpperCase()}</span><h1>{book.title}</h1><p>{book.description}</p><div className="detail-buttons"><a className="primary-button" href={pdfUrl(book)} download>Descargar PDF <Icon name="download" size={19}/></a><span>Lectura digital disponible abajo ↓</span></div></div></div></div><div className="reader-layout"><Sidebar book={book} items={items} active={active} setActive={setActive}/><article className="reader-paper"><div className="paper-header"><span>ATLAS VETERINARIO / {book.number}</span><span>EDICIÓN DIGITAL · 2026</span></div><ReaderBody book={book} active={active} setActive={setActive}/><div className="paper-foot"><span>ATLAS VETERINARIO</span><span>{String(active+1).padStart(2,'0')} / {String(items.length).padStart(2,'0')}</span></div></article></div><div className="medical-note">Material educativo sobre perros y gatos. No sustituye la evaluación clínica, la ficha técnica del producto ni los protocolos locales. Toda decisión de prescripción corresponde al médico veterinario responsable.</div></main>}

function App(){const [slug,setSlug]=useState(getSlug());function navigate(next){history.pushState({},'',next?'/material/'+next:'/');setSlug(next);window.scrollTo(0,0)}useEffect(()=>{let f=()=>setSlug(getSlug());window.addEventListener('popstate',f);return()=>window.removeEventListener('popstate',f)},[]);const book=books.find(x=>x.slug===slug);return <><Nav navigate={navigate} detail={!!book}/>{book?<Detail book={book} navigate={navigate}/>:<Home navigate={navigate}/>}<footer className="footer"><span className="brand-foot">✳ atlasveterinario</span><span>Material educativo · Edición 2026</span><button onClick={()=>{window.scrollTo({top:0,behavior:'smooth'})}}>Volver arriba ↑</button></footer></>}

createRoot(document.getElementById('root')).render(<App/>);
